name: main
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  code_assets: ^1.0.0
  hooks: ^1.0.0
  native_toolchain_c: ^0.17.3
  ffi: ^2.1.4



dev_dependencies:
  ffigen: ^20.0.0
  lints: ^6.0.0
  test: ^1.25.6
